// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Entities
{
    public partial class Generate_10_QResult
    {
        public int? Exam_ID { get; set; }
        public int Q_ID { get; set; }
    }
}
