// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Entities
{
    public partial class getInstructorCoursesResult
    {
        public string Crs_Name { get; set; }
        public int? NoOfStudents { get; set; }
    }
}
