// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Entities
{
    public partial class selectAllDepartmentResult
    {
        public int Dept_ID { get; set; }
        public string Dept_Name { get; set; }
        public string Dept_Location { get; set; }
        public int? Dept_Manager { get; set; }
        public DateTime? Manager_Hiredate { get; set; }
    }
}
