// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Entities
{
    public partial class selectAllStudentResult
    {
        public int St_ID { get; set; }
        public string St_FName { get; set; }
        public string St_LName { get; set; }
        public string St_Address { get; set; }
        public int? Dept_ID { get; set; }
    }
}
