// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Entities
{
    public partial class selectInsructorResult
    {
        public int Ins_ID { get; set; }
        public string Ins_Name { get; set; }
        public string Ins_Degree { get; set; }
        public int? salary { get; set; }
        public int? Dept_ID { get; set; }
    }
}
