// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Entities
{
    public partial class selectDept_InsResult
    {
        public int Dept_ID { get; set; }
        public int Ins_ID { get; set; }
    }
}
